spring:
  application:
    name: Transfer
  datasource:
    url: jdbc:h2:mem:transferdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

app:
  idempotency:
    ttl-hours: 24
  ledger:
    base-url: http://localhost:8081
    connect-timeout-ms: 2000
    read-timeout-ms: 5000